### ISSUE TITLE
New version alert

### ISSUE THREAD

**Issue by MHAcoustics** [openPSTD/openPSTD#83]
I just saw OpenPSTD-2.0.274 is posted. Is there a way that the internal PSTD community gets an e-mail alert when a new version is posted, or should we visit https://micfort.stackstorage.com/index.php/s/9VhBTCcUs5pjvgh 
every now and then to check for updates?

**Comment by micfort** [comment]
This is possible, but some days there are a lot of updates in a short time and a lot of updates aren't visible to the user. So this would spam your mail box and is not really advisable. 
If there are certain issues you are interest in, you can subscribe to that issue and get an update(mail) when that issue is finished or changes state. If the done correctly the code is changed and a update should be in progress and added to the list within 2 hours. If you created the issue, you are automatically subscribed. 
I close this issue, if there are any question about this, you can reopen the issue.
